spring:
  profiles: prod

  datasource:
    url: https://10.214.237.70
    name: devDatabase
    username: ${ENV_USERNAME}
    password: ${ENV_PASSWORD}


cloud:
  aws:
    s3endpoint: https://something.s3.ap-southeast-2.amazonaws.com/file1.txt
    accesskey: ${ENV_ACCESSKEY}
    secretkey: ${ENV_SECRETKEY}


