spring:
  profiles: test

  datasource:
    url: https://10.214.237.70
    name: testDatabase
    username: root
    password: root


cloud:
  aws:
    s3endpoint: https://something.s3.ap-southeast-2.amazonaws.com/file1.txt
    accesskey: thisistheaccessKey
    secretkey: thisisthesecretkey


